### PR TITLE
Refresh Continuous Integration scripts

### PR DESCRIPTION
**Pull request by traversaro**
* apt CI: bump version of yarp and ycm-cmake-modules used
* conda CI: bump version of used GitHub Actions

### CODE REVIEW

**Comment by traversaro** [comment]
For some reason, the CI is not running, I am not sure why.

**Comment by traversaro** [comment]
> For some reason, the CI is not running, I am not sure why.

It was disabled due to inactivity, I re-activated it.

**Comment by traversaro** [comment]
I re-activated the CI, and there is a test (ImuTest on macOS) consistently failing. So for now I just opened an issue to track the problem (https://github.com/robotology/gz-sim-yarp-plugins/issues/54) and skipped the test (https://github.com/robotology/gz-sim-yarp-plugins/pull/51/commits/f8bd5e3cb10d2d8745a4fb42a340f2b1acb2822c).

**Comment by traversaro** [comment]
Ok, with some skip the CI is now green, the PR is ready for review and merge.

**Review by xela-95 — APPROVED** [review]

**Pull request merged**
