### PR TITLE
Fix controlboard bug on resetPositionsAndTrajectoryGenerators at initial configuration

### LINKED ISSUE #108: Fix controlboard bug on `resetPositionsAndTrajectoryGenerators` at initial configuration
See https://github.com/robotology/gz-sim-yarp-plugins/issues/103#issuecomment-1978894636

### PR DESCRIPTION
**Pull request by xela-95**
Closes #108

### CODE REVIEW

**Comment by traversaro** [comment]
Do you have any idea why codecov continues to spam messages?

**Comment by xela-95** [comment]
> Do you have any idea why codecov continues to spam messages?

unfortunately my updates to the CI yaml were not effective... I think I need to create a separate `codecov.yaml` file to customize its behavior: https://docs.codecov.com/docs/codecov-yaml

**Comment by xela-95** [comment]
Anyhow it is possible to reproduce the exception I got in https://github.com/robotology/gz-sim-yarp-plugins/issues/103#issuecomment-1978894636 by launching the single pendulum tutorial and by commenting out the `<initialConfiguration>` block: 
https://github.com/robotology/gz-sim-yarp-plugins/blob/1e86adb9247b159900c4eae312222950fa0f70f1/tutorial/single_pendulum/model.sdf#L99

Also here I verified that I had an empty vector as the result of calling:
 https://github.com/robotology/gz-sim-yarp-plugins/blob/98f78ae5fff2fbcc8f5f240b3cb87475cded5451/plugins/controlboard/src/ControlBoard.cpp#L874

**Comment by xela-95** [comment]
We're getting (again) a failure in the macos tests, in particular on the new test implemented:
https://github.com/robotology/gz-sim-yarp-plugins/actions/runs/8160658434/job/22307711533?pr=109#step:12:50

```
 libc++abi: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
```

An interesting reference on SO: https://stackoverflow.com/questions/66773247/libcabi-dylib-terminating-with-uncaught-exception-of-type-std-1system-er

**Comment by xela-95** [comment]
> We're getting (again) a failure in the macos tests, in particular on the new test implemented: https://github.com/robotology/gz-sim-yarp-plugins/actions/runs/8160658434/job/22307711533?pr=109#step:12:50
> 
> ```
>  libc++abi: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
> ```
> 
> An interesting reference on SO: https://stackoverflow.com/questions/66773247/libcabi-dylib-terminating-with-uncaught-exception-of-type-std-1system-er

Also this could be related to the bug #102, since different platforms I'mplement locking mechanisms in different ways, this problem maybe shows up only on macOs...

**Comment by xela-95** [comment]
Since this macOS issue is not related to the current development and is already documented in #90, I will exclude the new test from it for the time being.

**Review by traversaro — APPROVED** [review]

**Comment by xela-95** [comment]
Test passed! Merging 🚀

**Pull request merged**
